---
- name: Deploy Squid Proxy
  hosts: squid
  become: true

  pre_tasks:
    - name: Verify host is reachable
      ansible.builtin.ping:

  roles:
    - role: common
      tags: common
    - role: squid
      tags: squid
