---
all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3.12
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: true
    ansible_become_method: sudo
  children:
    ntp_servers:
      hosts:
        ntp-01:
          ansible_host: <host-ip>
    dns_servers:
      hosts:
        dns-01:
          ansible_host: <host-ip>
    apt_repo:
      hosts:
        apt-repo-01:
          ansible_host: <host-ip>
    squid:
      hosts:
        squid-01:
          ansible_host: <host-ip>
    gitlab:
      hosts:
        gitlab-01:
          ansible_host: <host-ip>
    haproxy:
      hosts:
        haproxy-01:
          ansible_host: <host-ip>
    k8s_control_plane:
      hosts:
        k8s-controlplane-01:
          ansible_host: <host-ip>
        k8s-controlplane-02:
          ansible_host: <host-ip>
        k8s-controlplane-03:
          ansible_host: <host-ip>
    k8s_worker:
      hosts:
        k8s-worker-01:
          ansible_host: <host-ip>
        k8s-worker-02:
          ansible_host: <host-ip>
        k8s-worker-03:
          ansible_host: <host-ip>
    k8s:
      children:
        k8s_control_plane: {}
        k8s_worker: {}
