---
all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3.12
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: true
    ansible_become_method: sudo
  children:
    client:
      hosts:
        client:
          ansible_host: <host-ip>
    ntp:
      hosts:
        ntp:
          ansible_host: <host-ip>
    dns:
      hosts:
        dns:
          ansible_host: <host-ip>
    apt-mirror:
      hosts:
        apt-mirror:
          ansible_host: <host-ip>
    squid:
      hosts:
        squid:
          ansible_host: <host-ip>
    gitlab:
      hosts:
        gitlab:
          ansible_host: <host-ip>
    haproxy:
      hosts:
        haproxy:
          ansible_host: <host-ip>
    k8s_control_plane:
      hosts:
        k8s-controlplane-01:
          ansible_host: <host-ip>
        k8s-controlplane-02:
          ansible_host: <host-ip>
        k8s-controlplane-03:
          ansible_host: <host-ip>
    k8s_worker:
      hosts:
        k8s-worker-01:
          ansible_host: <host-ip>
        k8s-worker-02:
          ansible_host: <host-ip>
        k8s-worker-03:
          ansible_host: <host-ip>
    k8s:
      children:
        k8s_control_plane: {}
        k8s_worker: {}
