---

- name: Set DNS in resolved.conf 
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#?DNS=',         line: 'DNS=172.16.10.2 1.1.1.1' }
    - { regexp: '^#?FallbackDNS=', line: 'FallbackDNS=8.8.8.8' }
    - { regexp: '^#?Domains=',     line: 'Domains=nghia.internal' }
  notify: Restart systemd-resolved