---
all:
   children:
      client:
         hosts:
            client-01:
               ansible_host: 192.168.100.100
      foundation:
         hosts:
            squid:
               ansible_host: 172.16.10.1
            dns:
               ansible_host: 172.16.10.2
            ntpsec:
               ansible_host: 172.16.10.3
            apt_mirror:
               ansible_host: 172.16.10.4
      kubernetes:
         children:
            k8s_control_plane:
               hosts:
                  k8s-master-01:
                     ansible_host: 172.16.10.30
                  k8s-master-02:
                     ansible_host: 172.16.10.31
                  k8s-master-03:
                     ansible_host: 172.16.10.33
            k8s_worker:
               hosts:
                  k8s-worker-01:
                     ansible_host: 172.16.10.34
                  k8s-worker-02:
                     ansible_host: 172.16.10.35
                  k8s-worker-03:
                     ansible_host: 172.16.10.36
   vars:
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_user: root
      