# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/vars.json
squid_package_list:
  - squid
  - apache2-utils

squid_config_path: /etc/squid/conf.d/debian.conf
squid_passwd_path: /etc/squid/passwd
squid_cache_dir: /var/spool/squid
squid_log_dir: /var/log/squid
squid_service: squid