---
- name: Install packages
  ansible.builtin.import_tasks: install.yaml
  tags: install

- name: Configure authentication
  ansible.builtin.import_tasks: auth.yaml
  tags: auth

- name: Configure squid
  ansible.builtin.import_tasks: configure.yaml
  tags: configure
