--- 
- name: Restart timesyncd
  ansible.builtin.systemd:
     name: systemd-timesyncd
     state: restarted

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted