---
- name: Kubernetes preflight on all nodes
  hosts: kubernetes
  become: true
  roles:
    - role: k8s_preflight
      tags: preflight

- name: Install container runtime on all nodes
  hosts: kubernetes
  become: true
  roles:
    - role: k8s_containerd
      tags: containerd

- name: Install Kubernetes packages on all nodes
  hosts: kubernetes
  become: true
  roles:
    - role: k8s_install
      tags: k8s-install

- name: Initialize control plane
  hosts: k8s_control_plane
  become: true
  roles:
    - role: k8s_control_plane
      tags: control-plane

- name: Join worker nodes to cluster
  hosts: k8s_worker
  become: true
  roles:
    - role: k8s_worker
      tags: worker
