# Prepare VM/OS before installing services
# VM Proxy
common_proxy_enabled: true
common_proxy_url: "http://proxy.internal.local:3128"
common_no_proxy: "localhost,127.0.0.1,10.0.0.0/8,.internal.local"

# VM DNS
common_dns_servers:
  - "{{ hostvars['dns-01']['ansible_host'] }}"

# VM NTP
common_ntp_servers:
  - "{{ hostvars['ntp']['ansible_host'] }}"


