---
- import_playbook: playbooks/prepare-vm/main.yml
  tags: [prepare-vm]

- import_playbook: playbooks/basic-service/main.yml
  tags: [basic-service]

- import_playbook: playbooks/k8s-cluster/main.yml
  tags: [k8s]